export interface Application {
  sNo: number
  applicantId: string
  industry: "Services" | "Trading" | "Manufacturing"
  loanAmount: number
  loanCategory: string
  category: "Small" | "Medium" | "Large"
  incomeDocSubmitted: boolean
  kycSubmitted: boolean
  businessProofSubmitted: boolean
}

export type ApplicationStatus = "Ready for Appraisal" | "Conditional Approval" | "On Hold" | "Rejected"

export const getApplicationStatus = (app: Application): ApplicationStatus => {
  if (!app.kycSubmitted) {
    return "Rejected"
  }
  if (app.kycSubmitted && app.incomeDocSubmitted && app.businessProofSubmitted) {
    return "Ready for Appraisal"
  }
  if (app.kycSubmitted && app.incomeDocSubmitted && !app.businessProofSubmitted) {
    return "Conditional Approval"
  }
  if (app.kycSubmitted && !app.incomeDocSubmitted && app.businessProofSubmitted) {
    return "On Hold"
  }
  return "Rejected"
}

export const formatCurrency = (amount: number): string => {
  if (amount >= 10000000) {
    return `₹${(amount / 10000000).toFixed(2)} Cr`
  } else if (amount >= 100000) {
    return `₹${(amount / 100000).toFixed(2)} L`
  }
  return `₹${amount.toLocaleString("en-IN")}`
}

// Mock data for 250 SME applications
export const applications: Application[] = [
  {
    sNo: 1,
    applicantId: "SMEServ1",
    industry: "Services",
    loanAmount: 1000000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 2,
    applicantId: "SMETrad2",
    industry: "Trading",
    loanAmount: 4500000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 3,
    applicantId: "SMETrad3",
    industry: "Trading",
    loanAmount: 3100000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 4,
    applicantId: "SMEServ4",
    industry: "Services",
    loanAmount: 100000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 5,
    applicantId: "SMEServ5",
    industry: "Services",
    loanAmount: 1800000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 6,
    applicantId: "SMEServ6",
    industry: "Services",
    loanAmount: 1000000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 7,
    applicantId: "SMEServ7",
    industry: "Services",
    loanAmount: 2400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 8,
    applicantId: "SMEServ8",
    industry: "Services",
    loanAmount: 400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 9,
    applicantId: "SMEServ9",
    industry: "Services",
    loanAmount: 4600000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 10,
    applicantId: "SMEManu10",
    industry: "Manufacturing",
    loanAmount: 3700000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 11,
    applicantId: "SMEManu11",
    industry: "Manufacturing",
    loanAmount: 2100000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 12,
    applicantId: "SMETrad12",
    industry: "Trading",
    loanAmount: 900000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 13,
    applicantId: "SMETrad13",
    industry: "Trading",
    loanAmount: 2300000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 14,
    applicantId: "SMEServ14",
    industry: "Services",
    loanAmount: 4400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 15,
    applicantId: "SMEServ15",
    industry: "Services",
    loanAmount: 4500000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 16,
    applicantId: "SMETrad16",
    industry: "Trading",
    loanAmount: 1300000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 17,
    applicantId: "SMETrad17",
    industry: "Trading",
    loanAmount: 600000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 18,
    applicantId: "SMEManu18",
    industry: "Manufacturing",
    loanAmount: 5000000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 19,
    applicantId: "SMEServ19",
    industry: "Services",
    loanAmount: 1300000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 20,
    applicantId: "SMEManu20",
    industry: "Manufacturing",
    loanAmount: 300000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 21,
    applicantId: "SMEManu21",
    industry: "Manufacturing",
    loanAmount: 4800000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 22,
    applicantId: "SMEManu22",
    industry: "Manufacturing",
    loanAmount: 400000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 23,
    applicantId: "SMETrad23",
    industry: "Trading",
    loanAmount: 2700000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 24,
    applicantId: "SMEServ24",
    industry: "Services",
    loanAmount: 4900000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 25,
    applicantId: "SMEServ25",
    industry: "Services",
    loanAmount: 300000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 26,
    applicantId: "SMEManu26",
    industry: "Manufacturing",
    loanAmount: 4100000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 27,
    applicantId: "SMEServ27",
    industry: "Services",
    loanAmount: 900000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 28,
    applicantId: "SMEManu28",
    industry: "Manufacturing",
    loanAmount: 4600000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 29,
    applicantId: "SMEServ29",
    industry: "Services",
    loanAmount: 1100000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 30,
    applicantId: "SMEServ30",
    industry: "Services",
    loanAmount: 3900000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 31,
    applicantId: "SMEManu31",
    industry: "Manufacturing",
    loanAmount: 300000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 32,
    applicantId: "SMEServ32",
    industry: "Services",
    loanAmount: 400000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 33,
    applicantId: "SMEManu33",
    industry: "Manufacturing",
    loanAmount: 4200000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 34,
    applicantId: "SMEServ34",
    industry: "Services",
    loanAmount: 1300000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 35,
    applicantId: "SMEManu35",
    industry: "Manufacturing",
    loanAmount: 4800000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 36,
    applicantId: "SMEServ36",
    industry: "Services",
    loanAmount: 3800000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 37,
    applicantId: "SMEServ37",
    industry: "Services",
    loanAmount: 4200000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 38,
    applicantId: "SMEServ38",
    industry: "Services",
    loanAmount: 2900000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 39,
    applicantId: "SMEServ39",
    industry: "Services",
    loanAmount: 2300000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 40,
    applicantId: "SMEServ40",
    industry: "Services",
    loanAmount: 300000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 41,
    applicantId: "SMEServ41",
    industry: "Services",
    loanAmount: 4700000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 42,
    applicantId: "SMEManu42",
    industry: "Manufacturing",
    loanAmount: 1100000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 43,
    applicantId: "SMETrad43",
    industry: "Trading",
    loanAmount: 1500000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 44,
    applicantId: "SMETrad44",
    industry: "Trading",
    loanAmount: 4300000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 45,
    applicantId: "SMETrad45",
    industry: "Trading",
    loanAmount: 4700000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 46,
    applicantId: "SMEServ46",
    industry: "Services",
    loanAmount: 2000000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 47,
    applicantId: "SMETrad47",
    industry: "Trading",
    loanAmount: 2500000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 48,
    applicantId: "SMEServ48",
    industry: "Services",
    loanAmount: 1400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 49,
    applicantId: "SMEManu49",
    industry: "Manufacturing",
    loanAmount: 2900000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 50,
    applicantId: "SMEServ50",
    industry: "Services",
    loanAmount: 5000000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 51,
    applicantId: "SMEManu51",
    industry: "Manufacturing",
    loanAmount: 2100000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 52,
    applicantId: "SMEServ52",
    industry: "Services",
    loanAmount: 3400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 53,
    applicantId: "SMEManu53",
    industry: "Manufacturing",
    loanAmount: 3700000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 54,
    applicantId: "SMEServ54",
    industry: "Services",
    loanAmount: 2300000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 55,
    applicantId: "SMEManu55",
    industry: "Manufacturing",
    loanAmount: 4200000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 56,
    applicantId: "SMETrad56",
    industry: "Trading",
    loanAmount: 4900000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 57,
    applicantId: "SMETrad57",
    industry: "Trading",
    loanAmount: 4600000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 58,
    applicantId: "SMEManu58",
    industry: "Manufacturing",
    loanAmount: 2400000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 59,
    applicantId: "SMETrad59",
    industry: "Trading",
    loanAmount: 4800000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 60,
    applicantId: "SMETrad60",
    industry: "Trading",
    loanAmount: 2900000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 61,
    applicantId: "SMEServ61",
    industry: "Services",
    loanAmount: 3800000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 62,
    applicantId: "SMEServ62",
    industry: "Services",
    loanAmount: 1300000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 63,
    applicantId: "SMEManu63",
    industry: "Manufacturing",
    loanAmount: 2200000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 64,
    applicantId: "SMEServ64",
    industry: "Services",
    loanAmount: 4000000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 65,
    applicantId: "SMEManu65",
    industry: "Manufacturing",
    loanAmount: 3800000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 66,
    applicantId: "SMEServ66",
    industry: "Services",
    loanAmount: 3600000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 67,
    applicantId: "SMETrad67",
    industry: "Trading",
    loanAmount: 3300000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 68,
    applicantId: "SMEServ68",
    industry: "Services",
    loanAmount: 800000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 69,
    applicantId: "SMEServ69",
    industry: "Services",
    loanAmount: 3900000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 70,
    applicantId: "SMETrad70",
    industry: "Trading",
    loanAmount: 4300000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 71,
    applicantId: "SMETrad71",
    industry: "Trading",
    loanAmount: 3000000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 72,
    applicantId: "SMETrad72",
    industry: "Trading",
    loanAmount: 3000000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 73,
    applicantId: "SMEManu73",
    industry: "Manufacturing",
    loanAmount: 1800000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 74,
    applicantId: "SMEServ74",
    industry: "Services",
    loanAmount: 2400000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 75,
    applicantId: "SMEServ75",
    industry: "Services",
    loanAmount: 3200000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 76,
    applicantId: "SMETrad76",
    industry: "Trading",
    loanAmount: 2200000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 77,
    applicantId: "SMEServ77",
    industry: "Services",
    loanAmount: 1200000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 78,
    applicantId: "SMEServ78",
    industry: "Services",
    loanAmount: 3400000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 79,
    applicantId: "SMEManu79",
    industry: "Manufacturing",
    loanAmount: 1300000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 80,
    applicantId: "SMEServ80",
    industry: "Services",
    loanAmount: 2800000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 81,
    applicantId: "SMEManu81",
    industry: "Manufacturing",
    loanAmount: 4500000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 82,
    applicantId: "SMETrad82",
    industry: "Trading",
    loanAmount: 3200000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 83,
    applicantId: "SMEServ83",
    industry: "Services",
    loanAmount: 4700000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 84,
    applicantId: "SMEManu84",
    industry: "Manufacturing",
    loanAmount: 1600000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 85,
    applicantId: "SMETrad85",
    industry: "Trading",
    loanAmount: 2100000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 86,
    applicantId: "SMEServ86",
    industry: "Services",
    loanAmount: 3500000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 87,
    applicantId: "SMEManu87",
    industry: "Manufacturing",
    loanAmount: 4100000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 88,
    applicantId: "SMETrad88",
    industry: "Trading",
    loanAmount: 1400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 89,
    applicantId: "SMEServ89",
    industry: "Services",
    loanAmount: 2600000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 90,
    applicantId: "SMEManu90",
    industry: "Manufacturing",
    loanAmount: 3900000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 91,
    applicantId: "SMETrad91",
    industry: "Trading",
    loanAmount: 1800000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 92,
    applicantId: "SMEServ92",
    industry: "Services",
    loanAmount: 4400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 93,
    applicantId: "SMEManu93",
    industry: "Manufacturing",
    loanAmount: 2700000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 94,
    applicantId: "SMETrad94",
    industry: "Trading",
    loanAmount: 3600000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 95,
    applicantId: "SMEServ95",
    industry: "Services",
    loanAmount: 1500000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 96,
    applicantId: "SMEManu96",
    industry: "Manufacturing",
    loanAmount: 4800000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 97,
    applicantId: "SMETrad97",
    industry: "Trading",
    loanAmount: 2400000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 98,
    applicantId: "SMEServ98",
    industry: "Services",
    loanAmount: 3100000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 99,
    applicantId: "SMEManu99",
    industry: "Manufacturing",
    loanAmount: 1900000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 100,
    applicantId: "SMETrad100",
    industry: "Trading",
    loanAmount: 4200000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  // Additional 150 applications for complete dataset
  {
    sNo: 101,
    applicantId: "SMEServ101",
    industry: "Services",
    loanAmount: 2500000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 102,
    applicantId: "SMEManu102",
    industry: "Manufacturing",
    loanAmount: 3300000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 103,
    applicantId: "SMETrad103",
    industry: "Trading",
    loanAmount: 1700000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 104,
    applicantId: "SMEServ104",
    industry: "Services",
    loanAmount: 4100000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 105,
    applicantId: "SMEManu105",
    industry: "Manufacturing",
    loanAmount: 2800000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 106,
    applicantId: "SMETrad106",
    industry: "Trading",
    loanAmount: 3500000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 107,
    applicantId: "SMEServ107",
    industry: "Services",
    loanAmount: 1200000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 108,
    applicantId: "SMEManu108",
    industry: "Manufacturing",
    loanAmount: 4600000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 109,
    applicantId: "SMETrad109",
    industry: "Trading",
    loanAmount: 2200000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 110,
    applicantId: "SMEServ110",
    industry: "Services",
    loanAmount: 3800000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 111,
    applicantId: "SMEManu111",
    industry: "Manufacturing",
    loanAmount: 1400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 112,
    applicantId: "SMETrad112",
    industry: "Trading",
    loanAmount: 4900000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 113,
    applicantId: "SMEServ113",
    industry: "Services",
    loanAmount: 2600000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 114,
    applicantId: "SMEManu114",
    industry: "Manufacturing",
    loanAmount: 3100000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 115,
    applicantId: "SMETrad115",
    industry: "Trading",
    loanAmount: 1800000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 116,
    applicantId: "SMEServ116",
    industry: "Services",
    loanAmount: 4400000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 117,
    applicantId: "SMEManu117",
    industry: "Manufacturing",
    loanAmount: 2300000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 118,
    applicantId: "SMETrad118",
    industry: "Trading",
    loanAmount: 3700000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 119,
    applicantId: "SMEServ119",
    industry: "Services",
    loanAmount: 1500000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 120,
    applicantId: "SMEManu120",
    industry: "Manufacturing",
    loanAmount: 4200000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 121,
    applicantId: "SMETrad121",
    industry: "Trading",
    loanAmount: 2900000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 122,
    applicantId: "SMEServ122",
    industry: "Services",
    loanAmount: 3400000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 123,
    applicantId: "SMEManu123",
    industry: "Manufacturing",
    loanAmount: 1100000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 124,
    applicantId: "SMETrad124",
    industry: "Trading",
    loanAmount: 4700000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 125,
    applicantId: "SMEServ125",
    industry: "Services",
    loanAmount: 2100000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 126,
    applicantId: "SMEManu126",
    industry: "Manufacturing",
    loanAmount: 3600000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 127,
    applicantId: "SMETrad127",
    industry: "Trading",
    loanAmount: 1300000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 128,
    applicantId: "SMEServ128",
    industry: "Services",
    loanAmount: 4800000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 129,
    applicantId: "SMEManu129",
    industry: "Manufacturing",
    loanAmount: 2500000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 130,
    applicantId: "SMETrad130",
    industry: "Trading",
    loanAmount: 3900000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 131,
    applicantId: "SMEServ131",
    industry: "Services",
    loanAmount: 1600000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 132,
    applicantId: "SMEManu132",
    industry: "Manufacturing",
    loanAmount: 4400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 133,
    applicantId: "SMETrad133",
    industry: "Trading",
    loanAmount: 2700000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 134,
    applicantId: "SMEServ134",
    industry: "Services",
    loanAmount: 3200000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 135,
    applicantId: "SMEManu135",
    industry: "Manufacturing",
    loanAmount: 900000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 136,
    applicantId: "SMETrad136",
    industry: "Trading",
    loanAmount: 4500000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 137,
    applicantId: "SMEServ137",
    industry: "Services",
    loanAmount: 1900000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 138,
    applicantId: "SMEManu138",
    industry: "Manufacturing",
    loanAmount: 3400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 139,
    applicantId: "SMETrad139",
    industry: "Trading",
    loanAmount: 2400000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 140,
    applicantId: "SMEServ140",
    industry: "Services",
    loanAmount: 4100000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 141,
    applicantId: "SMEManu141",
    industry: "Manufacturing",
    loanAmount: 1700000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 142,
    applicantId: "SMETrad142",
    industry: "Trading",
    loanAmount: 3100000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 143,
    applicantId: "SMEServ143",
    industry: "Services",
    loanAmount: 2800000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 144,
    applicantId: "SMEManu144",
    industry: "Manufacturing",
    loanAmount: 4900000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 145,
    applicantId: "SMETrad145",
    industry: "Trading",
    loanAmount: 1400000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 146,
    applicantId: "SMEServ146",
    industry: "Services",
    loanAmount: 3700000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 147,
    applicantId: "SMEManu147",
    industry: "Manufacturing",
    loanAmount: 2200000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 148,
    applicantId: "SMETrad148",
    industry: "Trading",
    loanAmount: 4600000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 149,
    applicantId: "SMEServ149",
    industry: "Services",
    loanAmount: 1200000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 150,
    applicantId: "SMEManu150",
    industry: "Manufacturing",
    loanAmount: 3500000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 151,
    applicantId: "SMETrad151",
    industry: "Trading",
    loanAmount: 2600000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 152,
    applicantId: "SMEServ152",
    industry: "Services",
    loanAmount: 4300000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 153,
    applicantId: "SMEManu153",
    industry: "Manufacturing",
    loanAmount: 1800000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 154,
    applicantId: "SMETrad154",
    industry: "Trading",
    loanAmount: 3800000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 155,
    applicantId: "SMEServ155",
    industry: "Services",
    loanAmount: 2300000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 156,
    applicantId: "SMEManu156",
    industry: "Manufacturing",
    loanAmount: 4700000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 157,
    applicantId: "SMETrad157",
    industry: "Trading",
    loanAmount: 1500000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 158,
    applicantId: "SMEServ158",
    industry: "Services",
    loanAmount: 3300000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 159,
    applicantId: "SMEManu159",
    industry: "Manufacturing",
    loanAmount: 2100000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 160,
    applicantId: "SMETrad160",
    industry: "Trading",
    loanAmount: 4400000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 161,
    applicantId: "SMEServ161",
    industry: "Services",
    loanAmount: 1100000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 162,
    applicantId: "SMEManu162",
    industry: "Manufacturing",
    loanAmount: 3600000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 163,
    applicantId: "SMETrad163",
    industry: "Trading",
    loanAmount: 2800000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 164,
    applicantId: "SMEServ164",
    industry: "Services",
    loanAmount: 4800000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 165,
    applicantId: "SMEManu165",
    industry: "Manufacturing",
    loanAmount: 1600000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 166,
    applicantId: "SMETrad166",
    industry: "Trading",
    loanAmount: 3200000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 167,
    applicantId: "SMEServ167",
    industry: "Services",
    loanAmount: 2500000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 168,
    applicantId: "SMEManu168",
    industry: "Manufacturing",
    loanAmount: 4100000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 169,
    applicantId: "SMETrad169",
    industry: "Trading",
    loanAmount: 1300000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 170,
    applicantId: "SMEServ170",
    industry: "Services",
    loanAmount: 3900000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 171,
    applicantId: "SMEManu171",
    industry: "Manufacturing",
    loanAmount: 2400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 172,
    applicantId: "SMETrad172",
    industry: "Trading",
    loanAmount: 4500000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 173,
    applicantId: "SMEServ173",
    industry: "Services",
    loanAmount: 1700000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 174,
    applicantId: "SMEManu174",
    industry: "Manufacturing",
    loanAmount: 3400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 175,
    applicantId: "SMETrad175",
    industry: "Trading",
    loanAmount: 2900000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 176,
    applicantId: "SMEServ176",
    industry: "Services",
    loanAmount: 4200000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 177,
    applicantId: "SMEManu177",
    industry: "Manufacturing",
    loanAmount: 1400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 178,
    applicantId: "SMETrad178",
    industry: "Trading",
    loanAmount: 3700000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 179,
    applicantId: "SMEServ179",
    industry: "Services",
    loanAmount: 2200000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 180,
    applicantId: "SMEManu180",
    industry: "Manufacturing",
    loanAmount: 4900000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 181,
    applicantId: "SMETrad181",
    industry: "Trading",
    loanAmount: 1200000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 182,
    applicantId: "SMEServ182",
    industry: "Services",
    loanAmount: 3500000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 183,
    applicantId: "SMEManu183",
    industry: "Manufacturing",
    loanAmount: 2700000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 184,
    applicantId: "SMETrad184",
    industry: "Trading",
    loanAmount: 4600000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 185,
    applicantId: "SMEServ185",
    industry: "Services",
    loanAmount: 1800000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 186,
    applicantId: "SMEManu186",
    industry: "Manufacturing",
    loanAmount: 3100000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 187,
    applicantId: "SMETrad187",
    industry: "Trading",
    loanAmount: 2600000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 188,
    applicantId: "SMEServ188",
    industry: "Services",
    loanAmount: 4400000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 189,
    applicantId: "SMEManu189",
    industry: "Manufacturing",
    loanAmount: 1500000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 190,
    applicantId: "SMETrad190",
    industry: "Trading",
    loanAmount: 3800000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 191,
    applicantId: "SMEServ191",
    industry: "Services",
    loanAmount: 2100000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 192,
    applicantId: "SMEManu192",
    industry: "Manufacturing",
    loanAmount: 4300000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 193,
    applicantId: "SMETrad193",
    industry: "Trading",
    loanAmount: 1600000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 194,
    applicantId: "SMEServ194",
    industry: "Services",
    loanAmount: 3200000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 195,
    applicantId: "SMEManu195",
    industry: "Manufacturing",
    loanAmount: 2800000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 196,
    applicantId: "SMETrad196",
    industry: "Trading",
    loanAmount: 4700000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 197,
    applicantId: "SMEServ197",
    industry: "Services",
    loanAmount: 1300000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 198,
    applicantId: "SMEManu198",
    industry: "Manufacturing",
    loanAmount: 3600000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 199,
    applicantId: "SMETrad199",
    industry: "Trading",
    loanAmount: 2300000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 200,
    applicantId: "SMEServ200",
    industry: "Services",
    loanAmount: 4100000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 201,
    applicantId: "SMEManu201",
    industry: "Manufacturing",
    loanAmount: 1900000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 202,
    applicantId: "SMETrad202",
    industry: "Trading",
    loanAmount: 3400000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 203,
    applicantId: "SMEServ203",
    industry: "Services",
    loanAmount: 2400000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 204,
    applicantId: "SMEManu204",
    industry: "Manufacturing",
    loanAmount: 4800000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 205,
    applicantId: "SMETrad205",
    industry: "Trading",
    loanAmount: 1100000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 206,
    applicantId: "SMEServ206",
    industry: "Services",
    loanAmount: 3900000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 207,
    applicantId: "SMEManu207",
    industry: "Manufacturing",
    loanAmount: 2500000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 208,
    applicantId: "SMETrad208",
    industry: "Trading",
    loanAmount: 4200000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 209,
    applicantId: "SMEServ209",
    industry: "Services",
    loanAmount: 1700000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 210,
    applicantId: "SMEManu210",
    industry: "Manufacturing",
    loanAmount: 3300000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 211,
    applicantId: "SMETrad211",
    industry: "Trading",
    loanAmount: 2900000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 212,
    applicantId: "SMEServ212",
    industry: "Services",
    loanAmount: 4500000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 213,
    applicantId: "SMEManu213",
    industry: "Manufacturing",
    loanAmount: 1200000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 214,
    applicantId: "SMETrad214",
    industry: "Trading",
    loanAmount: 3700000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 215,
    applicantId: "SMEServ215",
    industry: "Services",
    loanAmount: 2200000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 216,
    applicantId: "SMEManu216",
    industry: "Manufacturing",
    loanAmount: 4600000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 217,
    applicantId: "SMETrad217",
    industry: "Trading",
    loanAmount: 1400000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 218,
    applicantId: "SMEServ218",
    industry: "Services",
    loanAmount: 3100000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 219,
    applicantId: "SMEManu219",
    industry: "Manufacturing",
    loanAmount: 2600000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 220,
    applicantId: "SMETrad220",
    industry: "Trading",
    loanAmount: 4900000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 221,
    applicantId: "SMEServ221",
    industry: "Services",
    loanAmount: 1600000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 222,
    applicantId: "SMEManu222",
    industry: "Manufacturing",
    loanAmount: 3500000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 223,
    applicantId: "SMETrad223",
    industry: "Trading",
    loanAmount: 2100000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 224,
    applicantId: "SMEServ224",
    industry: "Services",
    loanAmount: 4400000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 225,
    applicantId: "SMEManu225",
    industry: "Manufacturing",
    loanAmount: 1800000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 226,
    applicantId: "SMETrad226",
    industry: "Trading",
    loanAmount: 3200000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 227,
    applicantId: "SMEServ227",
    industry: "Services",
    loanAmount: 2700000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 228,
    applicantId: "SMEManu228",
    industry: "Manufacturing",
    loanAmount: 4100000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 229,
    applicantId: "SMETrad229",
    industry: "Trading",
    loanAmount: 1500000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 230,
    applicantId: "SMEServ230",
    industry: "Services",
    loanAmount: 3800000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 231,
    applicantId: "SMEManu231",
    industry: "Manufacturing",
    loanAmount: 2300000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 232,
    applicantId: "SMETrad232",
    industry: "Trading",
    loanAmount: 4700000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 233,
    applicantId: "SMEServ233",
    industry: "Services",
    loanAmount: 1300000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 234,
    applicantId: "SMEManu234",
    industry: "Manufacturing",
    loanAmount: 3400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 235,
    applicantId: "SMETrad235",
    industry: "Trading",
    loanAmount: 2800000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 236,
    applicantId: "SMEServ236",
    industry: "Services",
    loanAmount: 4200000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 237,
    applicantId: "SMEManu237",
    industry: "Manufacturing",
    loanAmount: 1900000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 238,
    applicantId: "SMETrad238",
    industry: "Trading",
    loanAmount: 3600000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 239,
    applicantId: "SMEServ239",
    industry: "Services",
    loanAmount: 2400000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 240,
    applicantId: "SMEManu240",
    industry: "Manufacturing",
    loanAmount: 4800000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 241,
    applicantId: "SMETrad241",
    industry: "Trading",
    loanAmount: 1200000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 242,
    applicantId: "SMEServ242",
    industry: "Services",
    loanAmount: 3900000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 243,
    applicantId: "SMEManu243",
    industry: "Manufacturing",
    loanAmount: 2600000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 244,
    applicantId: "SMETrad244",
    industry: "Trading",
    loanAmount: 4500000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: true,
  },
  {
    sNo: 245,
    applicantId: "SMEServ245",
    industry: "Services",
    loanAmount: 1700000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: false,
  },
  {
    sNo: 246,
    applicantId: "SMEManu246",
    industry: "Manufacturing",
    loanAmount: 3100000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 247,
    applicantId: "SMETrad247",
    industry: "Trading",
    loanAmount: 2500000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: true,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
  {
    sNo: 248,
    applicantId: "SMEServ248",
    industry: "Services",
    loanAmount: 4300000,
    loanCategory: "SME",
    category: "Medium",
    incomeDocSubmitted: false,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 249,
    applicantId: "SMEManu249",
    industry: "Manufacturing",
    loanAmount: 1400000,
    loanCategory: "SME",
    category: "Small",
    incomeDocSubmitted: true,
    kycSubmitted: true,
    businessProofSubmitted: true,
  },
  {
    sNo: 250,
    applicantId: "SMETrad250",
    industry: "Trading",
    loanAmount: 3700000,
    loanCategory: "SME",
    category: "Large",
    incomeDocSubmitted: false,
    kycSubmitted: false,
    businessProofSubmitted: false,
  },
]

export const kycDocuments = [
  { id: 1, name: "PAN Card of Business", category: "KYC" },
  { id: 2, name: "PAN Card of Business Owners", category: "KYC" },
  { id: 3, name: "Aadhaar Card of Business Owners", category: "KYC" },
  { id: 4, name: "Address Proof of Business Office", category: "KYC" },
]

export const incomeDocuments = [
  { id: 5, name: "Profit & Loss Statement (3 FY)", category: "Income Proof" },
  { id: 6, name: "Balance Sheet (3 FY)", category: "Income Proof" },
  { id: 7, name: "Income Tax Return (3 FY)", category: "Income Proof" },
  { id: 8, name: "Bank Statement (6-12 months)", category: "Income Proof" },
]

export const businessDocuments = [
  { id: 9, name: "Business Registration Document", category: "Business Proof" },
  { id: 10, name: "Corporate Identification Number", category: "Business Proof" },
  { id: 11, name: "List of Board of Directors", category: "Business Proof" },
]

export const smeClassification = [
  { category: "Micro", investment: "≤ ₹2.5 Crore", turnover: "≤ ₹10 Crore" },
  { category: "Small", investment: "≤ ₹25 Crore", turnover: "≤ ₹100 Crore" },
  { category: "Medium", investment: "≤ ₹125 Crore", turnover: "≤ ₹500 Crore" },
]
